import {
  Chapter,
  Comment,
  CommentVote,
  Follow,
  Notification,
  Page,
  PageHeat,
  RankingRollup,
  Reaction,
  Report,
  Series,
  User,
} from "@/lib/types";

const now = Date.now();
const minutesAgo = (n: number) => now - n * 60_000;
const hoursAgo = (n: number) => now - n * 60 * 60_000;
const daysAgo = (n: number) => now - n * 24 * 60 * 60_000;

export const usersSeed: User[] = [
  {
    _id: "user_reader_1",
    provider: "google",
    providerId: "google_reader_1",
    username: "inktraveler",
    avatarUrl: "https://picsum.photos/seed/reader1/80/80",
    bio: "Late-night chapter binges and live reactions.",
    isCreator: false,
    createdAt: daysAgo(180),
    lastActiveAt: minutesAgo(2),
    reputationScore: 48,
    isBanned: false,
  },
  {
    _id: "user_creator_1",
    provider: "discord",
    providerId: "discord_creator_1",
    username: "kei_arata",
    avatarUrl: "https://picsum.photos/seed/kei/80/80",
    bio: "Creator of Moonlit Blades.",
    isCreator: true,
    createdAt: daysAgo(420),
    lastActiveAt: minutesAgo(5),
    reputationScore: 280,
    isBanned: false,
  },
  {
    _id: "user_creator_2",
    provider: "apple",
    providerId: "apple_creator_2",
    username: "mina_oto",
    avatarUrl: "https://picsum.photos/seed/mina/80/80",
    bio: "Urban romance + rain-soaked panels.",
    isCreator: true,
    createdAt: daysAgo(510),
    lastActiveAt: minutesAgo(12),
    reputationScore: 261,
    isBanned: false,
  },
  {
    _id: "user_creator_3",
    provider: "google",
    providerId: "google_creator_3",
    username: "ren_kujo",
    avatarUrl: "https://picsum.photos/seed/ren/80/80",
    bio: "Action-heavy silent storytelling.",
    isCreator: true,
    createdAt: daysAgo(320),
    lastActiveAt: minutesAgo(20),
    reputationScore: 233,
    isBanned: false,
  },
  {
    _id: "user_mod_1",
    provider: "google",
    providerId: "google_mod_1",
    username: "seizuki_mod",
    avatarUrl: "https://picsum.photos/seed/mod/80/80",
    isCreator: false,
    createdAt: daysAgo(620),
    lastActiveAt: minutesAgo(1),
    reputationScore: 999,
    isBanned: false,
  },
];

export const seriesSeed: Series[] = [
  {
    _id: "series_moonlit_blades",
    creatorId: "user_creator_1",
    title: "Moonlit Blades",
    description: "A cursed sword school where students duel with memories instead of steel.",
    tags: ["Action", "Fantasy", "School"],
    language: "English",
    isMature: false,
    coverImageStorageId: "cover_moonlit_blades",
    readingMode: "MANGA",
    readingDirection: "RTL",
    status: "ACTIVE",
    createdAt: daysAgo(220),
    updatedAt: hoursAgo(3),
    averageRating: 4.8,
    ratingCount: 632,
  },
  {
    _id: "series_after_rain_tokyo",
    creatorId: "user_creator_2",
    title: "After Rain Tokyo",
    description: "Two strangers keep meeting under the same station roof after midnight.",
    tags: ["Romance", "Drama", "Slice of Life"],
    language: "English",
    isMature: false,
    coverImageStorageId: "cover_after_rain_tokyo",
    readingMode: "COMIC",
    readingDirection: "LTR",
    status: "ACTIVE",
    createdAt: daysAgo(170),
    updatedAt: hoursAgo(7),
    averageRating: 4.9,
    ratingCount: 401,
  },
  {
    _id: "series_hollow_kites",
    creatorId: "user_creator_3",
    title: "Hollow Kites",
    description: "A rooftop courier races across a collapsing megacity skyline.",
    tags: ["Sci-Fi", "Action", "Thriller"],
    language: "English",
    isMature: true,
    contentWarnings: ["Violence"],
    coverImageStorageId: "cover_hollow_kites",
    readingMode: "SCROLL",
    readingDirection: null,
    status: "ACTIVE",
    createdAt: daysAgo(200),
    updatedAt: hoursAgo(10),
    averageRating: 4.7,
    ratingCount: 517,
  },
];

export const chaptersSeed: Chapter[] = [
  {
    _id: "chapter_moonlit_42",
    seriesId: "series_moonlit_blades",
    creatorId: "user_creator_1",
    chapterNumber: 42,
    title: "The Shrine Duel",
    notes: "Thanks for reading! Overlay ON by default.",
    status: "PUBLISHED",
    publishedAt: hoursAgo(3),
    createdAt: daysAgo(5),
    updatedAt: hoursAgo(3),
    pageCount: 6,
    commentCount: 24,
    reactionCount: 96,
    viewCount: 8421,
  },
  {
    _id: "chapter_moonlit_43_draft",
    seriesId: "series_moonlit_blades",
    creatorId: "user_creator_1",
    chapterNumber: 43,
    title: "Night Oath",
    notes: "Draft work-in-progress.",
    status: "DRAFT",
    publishedAt: null,
    createdAt: daysAgo(1),
    updatedAt: hoursAgo(6),
    pageCount: 3,
    commentCount: 0,
    reactionCount: 0,
    viewCount: 0,
  },
  {
    _id: "chapter_rain_18",
    seriesId: "series_after_rain_tokyo",
    creatorId: "user_creator_2",
    chapterNumber: 18,
    title: "Platform 9, Last Train",
    status: "PUBLISHED",
    publishedAt: hoursAgo(7),
    createdAt: daysAgo(4),
    updatedAt: hoursAgo(7),
    pageCount: 5,
    commentCount: 18,
    reactionCount: 71,
    viewCount: 5222,
  },
  {
    _id: "chapter_hollow_31",
    seriesId: "series_hollow_kites",
    creatorId: "user_creator_3",
    chapterNumber: 31,
    title: "Skyline Collapse",
    status: "PUBLISHED",
    publishedAt: hoursAgo(10),
    createdAt: daysAgo(6),
    updatedAt: hoursAgo(10),
    pageCount: 7,
    commentCount: 39,
    reactionCount: 155,
    viewCount: 10_155,
  },
];

const pageImage = (seed: string, pageNumber: number) =>
  `https://picsum.photos/seed/${seed}-${pageNumber}/1300/1900`;

export const pagesSeed: Page[] = [
  ...Array.from({ length: 6 }, (_, index) => {
    const pageNumber = index + 1;
    return {
      _id: `page_moonlit_42_${pageNumber}`,
      chapterId: "chapter_moonlit_42",
      seriesId: "series_moonlit_blades",
      pageNumber,
      storageIdOriginal: `orig_moonlit_42_${pageNumber}`,
      storageIdLarge: `lg_moonlit_42_${pageNumber}`,
      storageIdMedium: `md_moonlit_42_${pageNumber}`,
      storageIdThumb: `th_moonlit_42_${pageNumber}`,
      width: 1300,
      height: 1900,
      bytes: 1_300_000,
      imageUrl: pageImage("moonlit42", pageNumber),
      createdAt: daysAgo(4),
    };
  }),
  ...Array.from({ length: 3 }, (_, index) => {
    const pageNumber = index + 1;
    return {
      _id: `page_moonlit_43_${pageNumber}`,
      chapterId: "chapter_moonlit_43_draft",
      seriesId: "series_moonlit_blades",
      pageNumber,
      storageIdOriginal: `orig_moonlit_43_${pageNumber}`,
      storageIdLarge: `lg_moonlit_43_${pageNumber}`,
      storageIdMedium: `md_moonlit_43_${pageNumber}`,
      storageIdThumb: `th_moonlit_43_${pageNumber}`,
      width: 1300,
      height: 1900,
      bytes: 1_240_000,
      imageUrl: pageImage("moonlit43", pageNumber),
      createdAt: daysAgo(1),
    };
  }),
  ...Array.from({ length: 5 }, (_, index) => {
    const pageNumber = index + 1;
    return {
      _id: `page_rain_18_${pageNumber}`,
      chapterId: "chapter_rain_18",
      seriesId: "series_after_rain_tokyo",
      pageNumber,
      storageIdOriginal: `orig_rain_18_${pageNumber}`,
      storageIdLarge: `lg_rain_18_${pageNumber}`,
      storageIdMedium: `md_rain_18_${pageNumber}`,
      storageIdThumb: `th_rain_18_${pageNumber}`,
      width: 1300,
      height: 1900,
      bytes: 1_180_000,
      imageUrl: pageImage("rain18", pageNumber),
      createdAt: daysAgo(3),
    };
  }),
  ...Array.from({ length: 7 }, (_, index) => {
    const pageNumber = index + 1;
    return {
      _id: `page_hollow_31_${pageNumber}`,
      chapterId: "chapter_hollow_31",
      seriesId: "series_hollow_kites",
      pageNumber,
      storageIdOriginal: `orig_hollow_31_${pageNumber}`,
      storageIdLarge: `lg_hollow_31_${pageNumber}`,
      storageIdMedium: `md_hollow_31_${pageNumber}`,
      storageIdThumb: `th_hollow_31_${pageNumber}`,
      width: 1300,
      height: 2200,
      bytes: 1_750_000,
      imageUrl: pageImage("hollow31", pageNumber),
      createdAt: daysAgo(5),
    };
  }),
];

export const commentsSeed: Comment[] = [
  {
    _id: "comment_1",
    chapterId: "chapter_moonlit_42",
    seriesId: "series_moonlit_blades",
    pageNumber: 2,
    authorId: "user_reader_1",
    parentCommentId: null,
    body: "That last panel hit hard.",
    createdAt: minutesAgo(10),
    isDeleted: false,
    isPinned: false,
    score: 8,
    upvoteCount: 9,
    downvoteCount: 1,
  },
  {
    _id: "comment_2",
    chapterId: "chapter_moonlit_42",
    seriesId: "series_moonlit_blades",
    pageNumber: 2,
    authorId: "user_creator_1",
    parentCommentId: "comment_1",
    body: "Thank you, I redrew that frame three times.",
    createdAt: minutesAgo(8),
    isDeleted: false,
    isPinned: false,
    score: 5,
    upvoteCount: 5,
    downvoteCount: 0,
  },
  {
    _id: "comment_3",
    chapterId: "chapter_moonlit_42",
    seriesId: "series_moonlit_blades",
    pageNumber: 3,
    authorId: "user_reader_1",
    parentCommentId: null,
    body: "I think the pacing is too slow here.",
    createdAt: minutesAgo(16),
    isDeleted: false,
    isPinned: false,
    score: -6,
    upvoteCount: 2,
    downvoteCount: 8,
  },
  {
    _id: "comment_4",
    chapterId: "chapter_hollow_31",
    seriesId: "series_hollow_kites",
    pageNumber: 5,
    authorId: "user_reader_1",
    parentCommentId: null,
    body: "The vertical flow is incredible in scroll mode.",
    createdAt: minutesAgo(11),
    isDeleted: false,
    isPinned: true,
    score: 14,
    upvoteCount: 15,
    downvoteCount: 1,
  },
  {
    _id: "comment_5",
    chapterId: "chapter_rain_18",
    seriesId: "series_after_rain_tokyo",
    pageNumber: 1,
    authorId: "user_reader_1",
    parentCommentId: null,
    body: "The station ambience is perfect.",
    createdAt: minutesAgo(22),
    isDeleted: false,
    isPinned: false,
    score: 7,
    upvoteCount: 7,
    downvoteCount: 0,
  },
];

export const commentVotesSeed: CommentVote[] = [
  {
    _id: "vote_1",
    commentId: "comment_1",
    voterId: "user_creator_1",
    value: 1,
    createdAt: minutesAgo(9),
  },
  {
    _id: "vote_2",
    commentId: "comment_3",
    voterId: "user_creator_1",
    value: -1,
    createdAt: minutesAgo(13),
  },
];

export const reactionsSeed: Reaction[] = [
  {
    _id: "reaction_1",
    chapterId: "chapter_moonlit_42",
    seriesId: "series_moonlit_blades",
    pageNumber: 2,
    userId: "user_reader_1",
    emoji: "🔥",
    createdAt: minutesAgo(1),
  },
  {
    _id: "reaction_2",
    chapterId: "chapter_moonlit_42",
    seriesId: "series_moonlit_blades",
    pageNumber: 2,
    userId: "user_creator_1",
    emoji: "👏",
    createdAt: minutesAgo(1),
  },
  {
    _id: "reaction_3",
    chapterId: "chapter_hollow_31",
    seriesId: "series_hollow_kites",
    pageNumber: 5,
    userId: "user_reader_1",
    emoji: "🤯",
    createdAt: minutesAgo(3),
  },
  {
    _id: "reaction_4",
    chapterId: "chapter_hollow_31",
    seriesId: "series_hollow_kites",
    pageNumber: 6,
    userId: "user_creator_3",
    emoji: "💯",
    createdAt: minutesAgo(2),
  },
];

export const followsSeed: Follow[] = [
  {
    _id: "follow_1",
    followerId: "user_reader_1",
    creatorId: "user_creator_1",
    createdAt: daysAgo(20),
  },
  {
    _id: "follow_2",
    followerId: "user_reader_1",
    creatorId: "user_creator_2",
    createdAt: daysAgo(10),
  },
];

export const notificationsSeed: Notification[] = [
  {
    _id: "notification_1",
    userId: "user_reader_1",
    type: "FOLLOWED_CREATOR_NEW_CHAPTER",
    payload: {
      creatorId: "user_creator_1",
      seriesId: "series_moonlit_blades",
      chapterId: "chapter_moonlit_42",
      message: "Kei Arata published Chapter 42",
    },
    isRead: false,
    createdAt: hoursAgo(3),
  },
  {
    _id: "notification_2",
    userId: "user_reader_1",
    type: "SYSTEM",
    payload: {
      message: "Overlay reactions are now enabled by default.",
    },
    isRead: true,
    createdAt: daysAgo(2),
  },
];

export const reportsSeed: Report[] = [
  {
    _id: "report_1",
    reporterId: "user_reader_1",
    targetType: "COMMENT",
    targetId: "comment_3",
    reason: "Harassment",
    details: "Personal attack in a reply",
    createdAt: daysAgo(1),
    status: "OPEN",
  },
];

export const rankingRollupsSeed: RankingRollup[] = [
  {
    _id: "rollup_week_trending",
    period: "WEEK",
    type: "TRENDING",
    items: [
      { chapterId: "chapter_hollow_31", score: 95, rank: 1 },
      { chapterId: "chapter_moonlit_42", score: 90, rank: 2 },
      { chapterId: "chapter_rain_18", score: 82, rank: 3 },
    ],
    computedAt: hoursAgo(2),
  },
  {
    _id: "rollup_week_most_discussed",
    period: "WEEK",
    type: "MOST_DISCUSSED",
    items: [
      { chapterId: "chapter_hollow_31", score: 39, rank: 1 },
      { chapterId: "chapter_moonlit_42", score: 24, rank: 2 },
      { chapterId: "chapter_rain_18", score: 18, rank: 3 },
    ],
    computedAt: hoursAgo(2),
  },
  {
    _id: "rollup_month_top_rated",
    period: "MONTH",
    type: "TOP_RATED",
    items: [
      { chapterId: "chapter_rain_18", score: 4.9, rank: 1 },
      { chapterId: "chapter_moonlit_42", score: 4.8, rank: 2 },
      { chapterId: "chapter_hollow_31", score: 4.7, rank: 3 },
    ],
    computedAt: hoursAgo(2),
  },
];

export const pageHeatSeed: PageHeat[] = [
  {
    _id: "heat_1",
    chapterId: "chapter_moonlit_42",
    pageNumber: 2,
    heatScore: 0.92,
    computedAt: hoursAgo(1),
  },
  {
    _id: "heat_2",
    chapterId: "chapter_hollow_31",
    pageNumber: 5,
    heatScore: 0.97,
    computedAt: hoursAgo(1),
  },
];
